### ISSUE TITLE
server crash for karma module

### ISSUE THREAD

**Issue by TimDaub** [attestate/kiwistand#107]
a user observed that the server crashes

2023-10-16T11:06:26: 2023-10-16T11:06:26.242Z @attestate/delegator2 Existing delegation for the
 "to" address: 0x03E16AF2f65Ac64054Dfb5480F7BE9B596ADC362
2023-10-16T11:06:26: file:///root/kiwistand/src/karma.mjs:7
2023-10-16T11:06:26:     .map((user) => user.submissions)
2023-10-16T11:06:26:                         ^
2023-10-16T11:06:26:
2023-10-16T11:06:26: TypeError: Cannot read properties of null (reading 'submissions')
2023-10-16T11:06:26:     at file:///root/kiwistand/src/karma.mjs:7:25
2023-10-16T11:06:26:     at Array.map (<anonymous>)
2023-10-16T11:06:26:     at getBaselineSubmissions (file:///root/kiwistand/src/karma.mjs:7:6)
2023-10-16T11:06:26:     at Module.score (file:///root/kiwistand/src/karma.mjs:31:31)
2023-10-16T11:06:26:     at file:///root/kiwistand/src/views/feed.mjs:219:53
2023-10-16T11:06:26:     at Array.map (<anonymous>)
2023-10-16T11:06:26:     at index (file:///root/kiwistand/src/views/feed.mjs:219:8)
2023-10-16T11:06:26:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-16T11:06:26:     at async default (file:///root/kiwistand/src/views/feed.mjs:271:51)
2023-10-16T11:06:26:     at async file:///root/kiwistand/src/http.mjs:111:21
2023-10-16T11:06:26:
2023-10-16T11:06:26: Node.js v19.9.0
2023-10-16T11:06:28: 2023-10-16T11:06:28.348Z @attestate/kiwistand Launching as bootstrap node

![photo1697454368](https://github.com/attestate/kiwistand/assets/2758453/9bd8f891-da77-4d20-aa3f-02d90816cc0e)

**Comment by TimDaub** [comment]
could be related

|kiwinews | 2023-10-16T16:52:57: TypeError: Cannot read properties of null (reading 'points')
0|kiwinews | 2023-10-16T16:52:57:     at Module.ranking (file:///root/kiwistand/src/karma.mjs:1
05:39)
0|kiwinews | 2023-10-16T16:52:57:     at default (file:///root/kiwistand/src/views/community.mjs:20:23)
0|kiwinews | 2023-10-16T16:52:57:     at file:///root/kiwistand/src/http.mjs:169:27
0|kiwinews | 2023-10-16T16:52:57:     at Layer.handle [as handle_request] (/root/kiwistand/node
_modules/express/lib/router/layer.js:95:5)
0|kiwinews | 2023-10-16T16:52:57:     at next (/root/kiwistand/node_modules/express/lib/router/
route.js:144:13)
0|kiwinews | 2023-10-16T16:52:57:     at Route.dispatch (/root/kiwistand/node_modules/express/l
ib/router/route.js:114:3)
0|kiwinews | 2023-10-16T16:52:57:     at Layer.handle [as handle_request] (/root/kiwistand/node
_modules/express/lib/router/layer.js:95:5)
0|kiwinews | 2023-10-16T16:52:57:     at /root/kiwistand/node_modules/express/lib/router/index.
js:284:15
0|kiwinews | 2023-10-16T16:52:57:     at Function.process_params (/root/kiwistand/node_modules/
express/lib/router/index.js:346:12)
