### ISSUE TITLE
local node crash

### ISSUE THREAD

**Issue by TimDaub** [attestate/kiwistand#141]
[1] file:///Users/timdaub/Projects/attestate/kiwistand/node_modules/it-length-prefixed/dist/src/decode.js:39
[1]                             throw errCode(new Error('message length too long'), 'ERR_MSG_DATA_TOO_LONG');
[1]                                           ^
[1]
[1] Error: message length too long
[1]     at decoder (file:///Users/timdaub/Projects/attestate/kiwistand/node_modules/it-length-prefixed/dist/src/decode.js:39:43)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async map (file:///Users/timdaub/Projects/attestate/kiwistand/node_modules/it-map/dist/src/index.js:6:22)
[1]     at async all (file:///Users/timdaub/Projects/attestate/kiwistand/node_modules/it-all/dist/src/index.js:6:22)
[1]     at async file:///Users/timdaub/Projects/attestate/kiwistand/src/sync.mjs:87:12
[1]     at async fromWire (file:///Users/timdaub/Projects/attestate/kiwistand/src/sync.mjs:81:10)
[1]     at async file:///Users/timdaub/Projects/attestate/kiwistand/src/sync.mjs:380:23 {
[1]   code: 'ERR_MSG_DATA_TOO_LONG'
[1] }
[1]
[1] Node.js v18.20.0
[1] npm run start exited with code 1

**Comment by TimDaub** [comment]
fixed with this one; https://github.com/attestate/kiwistand/commit/2bbbf4127884ddcd6e743908ccf38b91f78e9d18
