### ISSUE TITLE
dial request as no valid addresses

### ISSUE THREAD

**Issue by TimDaub** [attestate/kiwistand#149]
```
[1] 2024-09-12T20:15:30.307Z @attestate/kiwistand discovered 16Uiu2HAmV5fjAEpSzHbmgyqvGDvNwMLPtbFAFLVgw5qVwE86rzMh
[1] Message: initiate: error when sending levels
[1] Stack Trace: Error: The dial request has no valid addresses
[1]     at DefaultDialer.dial (file:///Users/timdaub/Projects/attestate/kiwistand/node_modules/libp2p/dist/src/connection-manager/dialer/index.js:92:27)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async DefaultConnectionManager.openConnection (file:///Users/timdaub/Projects/attestate/kiwistand/node_modules/libp2p/dist/src/connection-manager/index.js:345:32)
[1]     at async Libp2pNode.dial (file:///Users/timdaub/Projects/attestate/kiwistand/node_modules/libp2p/dist/src/libp2p.js:251:16)
[1]     at async Libp2pNode.dialProtocol (file:///Users/timdaub/Projects/attestate/kiwistand/node_modules/libp2p/dist/src/libp2p.js:261:28)
[1]     at async file:///Users/timdaub/Projects/attestate/kiwistand/src/sync.mjs:161:30
[1]     at async Module.initiate (file:///Users/timdaub/Projects/attestate/kiwistand/src/sync.mjs:214:16)
[1]     at async node.goblin.initiate (file:///Users/timdaub/Projects/attestate/kiwistand/src/index.mjs:88:12)
[1]     at async GossipSub.<anonymous> (file:///Users/timdaub/Projects/attestate/kiwistand/src/topics/roots.mjs:46:9)```

is caught and global peer is unset

**Comment by TimDaub** [comment]
Closing — error is caught and global peer is unset as designed; no confirmed impact since.
