### ISSUE TITLE
error when syncing

### ISSUE THREAD

**Issue by TimDaub** [attestate/kiwistand#31]
```
[1] 2023-05-02T14:25:01.126Z @attestate/kiwistand Initiating sync for peerId: "16Uiu2HAkwDvdncFUgr2f7AxBy9kJf6MtAERWHqEWsFWkNYJYbXEG" and level "0" and root "56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"
[1] 2023-05-02T14:25:05.172Z @attestate/kiwistand Topic name "_peer-discovery._p2p._pubsub" didn't match
[1] 2023-05-02T14:25:05.173Z @attestate/kiwistand Topic name "_peer-discovery._p2p._pubsub" didn't match
[1] 2023-05-02T14:25:05.173Z @attestate/kiwistand discovered 16Uiu2HAmFzqeeF18eXy4SRTN79Y6DkPgFjx8qJf2LmY4K35dR52K
[1] node:internal/event_target:1031
[1]   process.nextTick(() => { throw err; });
[1]                            ^
[1]
[1] [AggregateError: All promises were rejected] {
[1]   [errors]: [
[1]     AbortError: The operation was aborted
[1]         at EventTarget.onAbort (file:///Users/timdaub/Projects/attestate/kiwistand/node_modules/@libp2p/tcp/dist/src/index.js:81:22)
[1]         at [nodejs.internal.kHybridDispatch] (node:internal/event_target:756:20)
[1]         at EventTarget.dispatchEvent (node:internal/event_target:698:26)
[1]         at abortSignal (node:internal/abort_controller:308:10)
[1]         at AbortController.abort (node:internal/abort_controller:326:5)
[1]         at EventTarget.onAbort (/Users/timdaub/Projects/attestate/kiwistand/node_modules/any-signal/index.js:11:16)
[1]         at [nodejs.internal.kHybridDispatch] (node:internal/event_target:756:20)
[1]         at EventTarget.dispatchEvent (node:internal/event_target:698:26)
[1]         at abortSignal (node:internal/abort_controller:308:10)
[1]         at AbortController.abort (node:internal/abort_controller:326:5) {
[1]       code: 'ABORT_ERR',
[1]       type: 'aborted'
[1]     },
[1]     AbortError: The operation was aborted
[1]         at EventTarget.onAbort (file:///Users/timdaub/Projects/attestate/kiwistand/node_modules/@libp2p/tcp/dist/src/index.js:81:22)
[1]         at [nodejs.internal.kHybridDispatch] (node:internal/event_target:756:20)
[1]         at EventTarget.dispatchEvent (node:internal/event_target:698:26)
[1]         at abortSignal (node:internal/abort_controller:308:10)
[1]         at AbortController.abort (node:internal/abort_controller:326:5)
[1]         at EventTarget.onAbort (/Users/timdaub/Projects/attestate/kiwistand/node_modules/any-signal/index.js:11:16)
[1]         at [nodejs.internal.kHybridDispatch] (node:internal/event_target:756:20)
[1]         at EventTarget.dispatchEvent (node:internal/event_target:698:26)
[1]         at abortSignal (node:internal/abort_controller:308:10)
[1]         at AbortController.abort (node:internal/abort_controller:326:5) {
[1]       code: 'ABORT_ERR',
[1]       type: 'aborted'
[1]     },
[1]     Error: connect ECONNREFUSED 127.0.0.1:53462
[1]         at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
[1]       errno: -61,
[1]       code: 'ECONNREFUSED',
[1]       syscall: 'connect',
[1]       address: '127.0.0.1',
[1]       port: 53462
[1]     },
[1]     AbortError: The operation was aborted
[1]         at EventTarget.onAbort (file:///Users/timdaub/Projects/attestate/kiwistand/node_modules/@libp2p/tcp/dist/src/index.js:81:22)
[1]         at [nodejs.internal.kHybridDispatch] (node:internal/event_target:756:20)
[1]         at EventTarget.dispatchEvent (node:internal/event_target:698:26)
[1]         at abortSignal (node:internal/abort_controller:308:10)
[1]         at AbortController.abort (node:internal/abort_controller:326:5)
[1]         at EventTarget.onAbort (/Users/timdaub/Projects/attestate/kiwistand/node_modules/any-signal/index.js:11:16)
[1]         at [nodejs.internal.kHybridDispatch] (node:internal/event_target:756:20)
[1]         at EventTarget.dispatchEvent (node:internal/event_target:698:26)
[1]         at abortSignal (node:internal/abort_controller:308:10)
[1]         at AbortController.abort (node:internal/abort_controller:326:5) {
[1]       code: 'ABORT_ERR',
[1]       type: 'aborted'
[1]     }
[1]   ]
[1] }
[1]

```

**Comment by TimDaub** [comment]
seems to be related

```
{"level":3,"key":"643b","hash":"4fec573cac239bdf7da6e06d7a3ba46bef32a2a6fc8f897d01f63e387f710b41","node":"e21ea01967b9f1c4e25d9081d1ee2d0b0e228da50dce4906020cfc7ccf2bfd96ac3132"}]}"
[1] 2023-05-02T14:39:33.754Z @attestate/kiwistand receiving message: "undefined"
[1] 2023-05-02T14:39:33.754Z @attestate/kiwistand Received levels and comparing them
[1] file:///kiwistand/src/sync.mjs:81
[1]   for (let node of nodes) {
[1]                    ^
[1]
[1] TypeError: nodes is not iterable
[1]     at deserialize (kiwistand/src/sync.mjs:81:20)
[1]     at compare (kiwistand/src/sync.mjs:167:5)
[1]     at file:///kiwistand/src/sync.mjs:194:26
[1]     at file:///kiwistand/src/sync.mjs:180:28
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1] npm run start exited with code 1
```

**Comment by TimDaub** [comment]
related branch: https://github.com/attestate/kiwistand/compare/fix-sync-issues?expand=1
