### ISSUE TITLE
Node crash: stream ended before 1 bytes became available

### ISSUE THREAD

**Issue by freeatnet** [attestate/kiwistand#36]
```
  @attestate/kiwistand Topic name "goblin/v0.0.1/roots" didn't match +6ms
  @attestate/kiwistand Initiating sync for peerId: "16Uiu2HAmRQtP3LgAnmvpux9msdckMGsv5m2gFhiWFUGcYMGoyxro" and level "0" and root "cab1a17c0f0f739265f58567900dcf35c99c395df2673da630842c09646235bf" +0ms
  @attestate/kiwistand Initiating sync for peerId: "16Uiu2HAmRQtP3LgAnmvpux9msdckMGsv5m2gFhiWFUGcYMGoyxro" and level "1" and root "cab1a17c0f0f739265f58567900dcf35c99c395df2673da630842c09646235bf" +282ms
  @attestate/kiwistand Initiating sync for peerId: "16Uiu2HAmRQtP3LgAnmvpux9msdckMGsv5m2gFhiWFUGcYMGoyxro" and level "2" and root "cab1a17c0f0f739265f58567900dcf35c99c395df2673da630842c09646235bf" +255ms
  @attestate/kiwistand Initiating sync for peerId: "16Uiu2HAmRQtP3LgAnmvpux9msdckMGsv5m2gFhiWFUGcYMGoyxro" and level "3" and root "cab1a17c0f0f739265f58567900dcf35c99c395df2673da630842c09646235bf" +200ms
  @attestate/kiwistand Topic name "_peer-discovery._p2p._pubsub" didn't match +12ms
  @attestate/kiwistand Topic name "_peer-discovery._p2p._pubsub" didn't match +0ms
  @attestate/kiwistand discovered 16Uiu2HAmFzqeeF18eXy4SRTN79Y6DkPgFjx8qJf2LmY4K35dR52K +1ms
  @attestate/kiwistand Sending missing leaves to peer node +161ms
  @attestate/kiwistand Initiating sync for peerId: "16Uiu2HAmRQtP3LgAnmvpux9msdckMGsv5m2gFhiWFUGcYMGoyxro" and level "4" and root "cab1a17c0f0f739265f58567900dcf35c99c395df2673da630842c09646235bf" +387ms
  @attestate/kiwistand Initiating sync for peerId: "16Uiu2HAmRQtP3LgAnmvpux9msdckMGsv5m2gFhiWFUGcYMGoyxro" and level "5" and root "cab1a17c0f0f739265f58567900dcf35c99c395df2673da630842c09646235bf" +271ms
  @attestate/kiwistand Sending missing leaves to peer node +230ms
  @attestate/kiwistand Initiating sync for peerId: "16Uiu2HAmRQtP3LgAnmvpux9msdckMGsv5m2gFhiWFUGcYMGoyxro" and level "6" and root "cab1a17c0f0f739265f58567900dcf35c99c395df2673da630842c09646235bf" +442ms
  @attestate/kiwistand Sending missing leaves to peer node +207ms
  @attestate/kiwistand Initiating sync for peerId: "16Uiu2HAmRQtP3LgAnmvpux9msdckMGsv5m2gFhiWFUGcYMGoyxro" and level "7" and root "cab1a17c0f0f739265f58567900dcf35c99c395df2673da630842c09646235bf" +298ms
  @attestate/kiwistand Sending missing leaves to peer node +232ms
  @attestate/kiwistand Error sending leaves to peer +14ms
node:internal/event_target:1012
  process.nextTick(() => { throw err; });
                           ^

Error: stream ended before 1 bytes became available
    at file:///root/kiwistand/node_modules/it-reader/dist/src/index.js:32:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.next (file:///root/kiwistand/node_modules/@libp2p/multistream-select/dist/src/multistream.js:46:27)
    at async abortable (file:///root/kiwistand/node_modules/abortable-iterator/dist/src/index.js:28:26)
    at async decoder (file:///root/kiwistand/node_modules/it-length-prefixed/dist/src/decode.js:28:26)
    at async first (/root/kiwistand/node_modules/@libp2p/multistream-select/node_modules/it-first/index.js:11:20)
    at async file:///root/kiwistand/node_modules/@libp2p/multistream-select/dist/src/multistream.js:58:114
    at async read (file:///root/kiwistand/node_modules/@libp2p/multistream-select/dist/src/multistream.js:58:17)
    at async Module.readString (file:///root/kiwistand/node_modules/@libp2p/multistream-select/dist/src/multistream.js:68:17)
    at async Module.select (file:///root/kiwistand/node_modules/@libp2p/multistream-select/dist/src/select.js:23:20) {
  code: 'ERR_UNDER_READ',
  buffer: Uint8ArrayList { bufs: [], length: 0 }
}
```

**Comment by TimDaub** [comment]
many bug fixes for sync in v0.3.0 release so closing this issue
