### ISSUE TITLE
there are cases when a sync erorrs and then the global sync peer isn't reset back (and a node isn't able to continue to sync)

### ISSUE THREAD

**Issue by TimDaub** [attestate/kiwistand#45]
```
2023-05-05T22:16:21: 2023-05-05T22:16:21.507Z @attestate/kiwistand handle levels: Curren
tly syncing with "16Uiu2HAmSJ28LtYLwfknWbp4i81FsdLvueRdBnCB3FUpsJz1mGjM" but received le
vels from "16Uiu2HAmH9DBVos4MvYnjHPZ224PzN6ohPMQCpLa84gRdpnc6d4E". Aborting
2023-05-05T22:16:21: 2023-05-05T22:16:21.507Z @attestate/kiwistand Closing stream as res
ponse is missing
```

also, in this case, an node just closes the stream but it'd be nice if it'd tell the other node that it has no capacity.

**Comment by TimDaub** [comment]
- first message here is unsetting peer from syncing peer
- then connecting to 16Uiu2HAkvhpb3ShBp939BLBRLq6FJQnioYePuGW5dbzWJ47wA4Ag it seems to run into a condition it cannot handle
- most likely this line where it cannot handle "response" being undefined: https://github.com/attestate/kiwistand/blob/f85c60b55676f06fa741d7e21c2069e427dd6e78/src/sync.mjs#L195
```
[1] 2023-05-07T20:42:05.503Z @attestate/kiwistand Unsetting global peer
[1] 2023-05-07T20:42:06.276Z @attestate/kiwistand Topic name "_peer-discovery._p2p._pubsub" didn't match
[1] 2023-05-07T20:42:06.276Z @attestate/kiwistand Topic name "_peer-discovery._p2p._pubsub" didn't match
[1] 2023-05-07T20:42:06.276Z @attestate/kiwistand discovered 16Uiu2HAkvhpb3ShBp939BLBRLq6FJQnioYePuGW5dbzWJ47wA4Ag
[1] 2023-05-07T20:42:06.336Z @attestate/kiwistand Topic name "kiwi/0.0.1/roots" didn't match
[1] 2023-05-07T20:42:06.336Z @attestate/kiwistand Setting global peer: "16Uiu2HAkvhpb3ShBp939BLBRLq6FJQnioYePuGW5dbzWJ47wA4Ag"
[1] 2023-05-07T20:42:06.336Z @attestate/kiwistand Initiating sync for peerId: "16Uiu2HAkvhpb3ShBp939BLBRLq6FJQnioYePuGW5dbzWJ47wA4Ag" and level "0" and root "45c5fedb0a860031b4bca3d4e491d81f099f36e233a10429edc35e86f21e522c"
[1] node:internal/event_target:1031
[1]   process.nextTick(() => { throw err; });
[1]                            ^
[1]
[1] TypeError: Cannot read properties of undefined (reading 'missing')
[1]     at Module.initiate (file:///Users/timdaub/Projects/attestate/kiwistand/src/sync.mjs:195:40)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async node.goblin.initiate (file:///Users/timdaub/Projects/attestate/kiwistand/src/index.mjs:85:12)
[1]     at async GossipSub.<anonymous> (file:///Users/timdaub/Projects/attestate/kiwistand/src/topics/roots.mjs:44:7)
[1]
[1] Node.js v19.6.0
[1] npm run start exited with code 1
```

and then I looked at the logs of node "...4Ag"

```
2023-05-07T20:41:51: 2023-05-07T20:41:51.587Z @attestate/kiwistand discovered 16Uiu2HAmF
zqeeF18eXy4SRTN79Y6DkPgFjx8qJf2LmY4K35dR52K
2023-05-07T20:41:57: 2023-05-07T20:41:57.033Z @attestate/kiwistand Advertising new root
to peers: "kiwi/0.0.1/roots" and message: "�^@^Adrootx@4e291b7b75a3e76692a1cac48c2cc9397
5260802d41f3407b89a0f2719e2edcc"
2023-05-07T20:41:57: 2023-05-07T20:41:57.310Z @attestate/kiwistand receiving message: "[
{"level":0,"key":"","hash":"45c5fedb0a860031b4bca3d4e491d81f099f36e233a10429edc35e86f21e
522c","node":"e4820064a039b999e59dcee682f44986bf22710214c6049337e6786d3aae7224fcce608641
"}]"
2023-05-07T20:41:57: 2023-05-07T20:41:57.311Z @attestate/kiwistand handle levels: Curren
tly syncing with "16Uiu2HAmFzqeeF18eXy4SRTN79Y6DkPgFjx8qJf2LmY4K35dR52K" but received le
vels from "16Uiu2HAmCLsmmF57UASVWUh8EgYAYGHwo5o9QJFcUGVHK7srbW1z". Aborting
```
so it seems this is the same issue

**Comment by TimDaub** [comment]
2023-05-10T15:05:51: 2023-05-10T15:05:51.247Z @attestate/kiwistand receiving message: "[{"level":0,"key":"","hash":"56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363
b421","node":null}]"
2023-05-10T15:05:51: 2023-05-10T15:05:51.247Z @attestate/kiwistand handle levels: Currently syncing with "16Uiu2HAmE9sAH5RfUEi6FvF5LS8J1mRpMaCQbSb41rP6Pmhqpm1m" but received levels from "16Uiu2HAmMdLCy327AYPDFJut2ZyfzbaLkgBr4t8NyWP7zt8swNXD". Aborting


seems to still be the case

**Comment by TimDaub** [comment]
[1] 2023-05-29T18:49:47.944Z @attestate/kiwistand Topic name "kiwi/0.0.1/roots" didn't match
[1] 2023-05-29T18:49:47.944Z @attestate/kiwistand initiate: Currently syncing with "16Uiu2HAkvhpb3ShBp939BLBRLq6FJQnioYePuGW5dbzWJ47wA4Ag" but tried initiating with "16Uiu2HAmFzqeeF18eXy4SRTN79Y6DkPgFjx8qJf2LmY4K35dR52K". Aborting


could be connected to #53
