### ISSUE TITLE
changes to the mod file can crash the server

### ISSUE THREAD

**Issue by TimDaub** [attestate/kiwistand#51]
2023-05-11T14:30:07: 2023-05-11T14:30:07.370Z @attestate/crawler:lifecycle Waiting "60000ms" to repeat the task
2023-05-11T14:30:41: file:///root/kiwistand/src/views/moderation.mjs:20
2023-05-11T14:30:41:     throw new Error("Couldn't convert to JSON");
2023-05-11T14:30:41:           ^
2023-05-11T14:30:41: 
2023-05-11T14:30:41: Error: Couldn't convert to JSON
2023-05-11T14:30:41:     at Module.getConfig (file:///root/kiwistand/src/views/moderation.mjs:20:11)
2023-05-11T14:30:41:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-05-11T14:30:41:     at async editors (file:///root/kiwistand/src/views/feed.mjs:99:22)
2023-05-11T14:30:41:     at async index (file:///root/kiwistand/src/views/feed.mjs:125:35)
2023-05-11T14:30:41:     at async file:///root/kiwistand/src/http.mjs:131:21
2023-05-11T14:30:41: 

moderation parsing is very flakey

**Comment by TimDaub** [comment]
should not happen anymore: https://github.com/attestate/kiwistand/commit/f9f3d34bbae76973df7fd4aec42a231dcd292099
