### ISSUE TITLE
error when synching node 

### ISSUE THREAD

**Issue by TimDaub** [attestate/kiwistand#67]
0|kiwinews  | 2023-06-15T16:04:48: 2023-06-15T16:04:48.222Z @attestate/kiwistand Initiating syn
c for peerId: "16Uiu2HAmEiMEDGPP2mz1HV8RNaDJL1oj9jqVHeB2ngoypaDJU9Pd" and level "105" and root "abc23b2044bb3e5cd7e0de7edf8f4e519da3ad23517f5f9cf4c65d75f5814e23"                             0|kiwinews  | 2023-06-15T16:04:48: node:internal/event_target:1036                             0|kiwinews  | 2023-06-15T16:04:48:   process.nextTick(() => { throw err; });                   0|kiwinews  | 2023-06-15T16:04:48:                            ^
0|kiwinews  | 2023-06-15T16:04:48:                                                             0|kiwinews  | 2023-06-15T16:04:48: Error: Muxer already closed                                 0|kiwinews  | 2023-06-15T16:04:48:     at MplexStreamMuxer.newStream (file:///root/kiwistand/node_modules/@libp2p/mplex/dist/src/mplex.js:85:19)
0|kiwinews  | 2023-06-15T16:04:48:     at ConnectionImpl.newStream [as _newStream] (file:///roo
t/kiwistand/node_modules/libp2p/dist/src/upgrader.js:320:49)
0|kiwinews  | 2023-06-15T16:04:48:     at ConnectionImpl.newStream (file:///root/kiwistand/node
_modules/@libp2p/connection/dist/src/index.js:55:35)
0|kiwinews  | 2023-06-15T16:04:48:     at Libp2pNode.dialProtocol (file:///root/kiwistand/node_
modules/libp2p/dist/src/libp2p.js:262:33)
0|kiwinews  | 2023-06-15T16:04:48:     at process.processTicksAndRejections (node:internal/proc
ess/task_queues:95:5)                                                                          0|kiwinews  | 2023-06-15T16:04:48:     at async file:///root/kiwistand/src/sync.mjs:152:30
0|kiwinews  | 2023-06-15T16:04:48:     at async initiate (file:///root/kiwistand/src/sync.mjs:204:20)
0|kiwinews  | 2023-06-15T16:04:48:     at async initiate (file:///root/kiwistand/src/sync.mjs:238:10)
0|kiwinews  | 2023-06-15T16:04:48:     at async initiate (file:///root/kiwistand/src/sync.mjs

**Comment by mattleesounds** [comment]
[1] 2023-06-15T16:04:48.128Z @attestate/kiwistand put: Didn't add message to database because of error: "Error: Address "0x3e6c23CdAa52B1B6621dBb30c367d16ace21F760" wasn't found in the allow list. Dropping message "{"href":"https://metaversal.banklesshq.com/p/erc-6551","signature":"0x2daa8ef2c9745d429c8c80734bbd0006d13c9b8d95ceec090f14abf1bfc759af321d3daa81e16f13e8417f0f7fc8e219b88ac4844e757194f1fbcc30f8d0a4581b","timestamp":1684474156,"title":"ERC-6551: The NFT Game-Changer 🎆","type":"amplify"}"."
[1] file:///Users/matthewlee/projects/kiwistand/node_modules/lmdb/read.js:697
[1]                                     readTxn = new Txn(env, 0x20000, lastReadTxn && !lastReadTxn.isDone && lastReadTxn);
[1]                                               ^
[1] 
[1] Error: MDB_READERS_FULL: Environment maxreaders limit reached
[1]     at renewReadTxn (file:///Users/matthewlee/projects/kiwistand/node_modules/lmdb/read.js:697:16)
[1]     at resetCursor (file:///Users/matthewlee/projects/kiwistand/node_modules/lmdb/read.js:367:81)
[1]     at RangeIterable.iterable.iterate (file:///Users/matthewlee/projects/kiwistand/node_modules/lmdb/read.js:391:5)
[1]     at RangeIterable.[Symbol.iterator] (file:///Users/matthewlee/projects/kiwistand/node_modules/lmdb/util/RangeIterable.js:75:31)
[1]     at Function.from (<anonymous>)
[1]     at Module.all (file:///Users/matthewlee/projects/kiwistand/node_modules/@attestate/crawler/src/database.mjs:43:16)
[1]     at async Module.allowlist (file:///Users/matthewlee/projects/kiwistand/src/chainstate/registry.mjs:15:15)
[1]     at async put (file:///Users/matthewlee/projects/kiwistand/src/sync.mjs:256:23)
[1]     at async file:///Users/matthewlee/projects/kiwistand/src/sync.mjs:326:5
[1]     at async file:///Users/matthewlee/projects/kiwistand/src/sync.mjs:288:22 {
[1]   code: -30790
[1] }
[1] npm run start exited with code 1

**Comment by TimDaub** [comment]
- what rpc node provider are you using?
- are you a paying customer or are they rate limiting you?
- what does /api/v1/allowlist of the http api return?
